// Static fallback data — used when Django API is unavailable

export const education = [
  {
    id: 1,
    institution: 'Lovely Professional University',
    degree: 'B.Tech – Computer Science & Engineering',
    grade: 'CGPA: 7.61',
    period: 'Aug 2023 – Present',
    location: 'Punjab, India',
    type: 'university',
    icon: '🎓',
    color: 'cyan',
  },
  {
    id: 2,
    institution: 'Siddharth Public School',
    degree: 'Intermediate (Class XII)',
    grade: '77%',
    period: 'Apr 2022 – Mar 2023',
    location: 'Siddharth Nagar, Uttar Pradesh',
    type: 'school',
    icon: '📚',
    color: 'purple',
  },
  {
    id: 3,
    institution: 'Blue Ink School International',
    degree: 'Matriculation (Class X)',
    grade: '75%',
    period: 'Apr 2020 – Mar 2021',
    location: 'Siddharth Nagar, Uttar Pradesh',
    type: 'school',
    icon: '🏫',
    color: 'blue',
  },
];

export const projects = {
  web: [
    {
      id: 1,
      title: 'Electro Shop Management System',
      category: 'web',
      description:
        'A comprehensive full-stack shop management system with inventory tracking, sales analytics dashboard, invoice management, and payment tracking.',
      longDescription:
        'The Electro Shop Management System is a production-ready full-stack application that streamlines shop operations. Powered by Django REST Framework on the backend and Next.js on the frontend, it provides real-time inventory management, analytics charts (Matplotlib/Seaborn), seamless invoice generation, and a complete payment tracking module.',
      features: [
        'Real-time inventory management with stock alerts',
        'Sales analytics dashboard powered by Matplotlib & Seaborn',
        'Invoice generation and management system',
        'Payment tracking with transaction history',
        'Admin dashboard with role-based access',
      ],
      tech_stack: ['Python', 'Django', 'DRF', 'React', 'Next.js', 'Tailwind CSS', 'Matplotlib', 'Seaborn', 'SQLite'],
      github_url: 'https://github.com/manojagragari',
      live_url: null,
      featured: true,
      order: 1,
      gradient: 'from-cyan-500/20 to-blue-500/20',
      accentColor: 'cyan',
    },
    {
      id: 2,
      title: 'Personal Learning & Notes Platform',
      category: 'web',
      description:
        'A personal platform for organizing learning resources, tracking progress, and managing notes with a clean intuitive interface.',
      longDescription:
        'The Personal Learning & Notes Platform is a purpose-built productivity tool for students and self-learners. Built entirely with Next.js and Tailwind CSS, it provides a smooth experience for note taking, resource organization, and progress tracking.',
      features: [
        'Organized note management by topics and subjects',
        'Learning progress tracker with visual stats',
        'Resource and bookmark management',
        'Responsive and accessible UI',
      ],
      tech_stack: ['Next.js', 'React', 'JavaScript', 'Tailwind CSS'],
      github_url: 'https://github.com/manojagragari',
      live_url: null,
      featured: true,
      order: 2,
      gradient: 'from-purple-500/20 to-pink-500/20',
      accentColor: 'purple',
    },
  ],
  android: [
    {
      id: 3,
      title: 'CGPA Calculator Android App',
      category: 'android',
      description:
        'A modern Android application to calculate and track CGPA throughout the academic year with a beautiful, intuitive Material Design interface.',
      longDescription:
        'The CGPA Calculator Android App helps students calculate and track their Cumulative Grade Point Average with ease. Built with Jetpack Compose for a declarative UI, it supports multi-semester management, visualizes grade distributions, and provides instant CGPA feedback.',
      features: [
        'Instant CGPA calculation with grade input',
        'Semester-wise grade management',
        'Visual grade distribution charts',
        'Modern Jetpack Compose Material Design UI',
        'Offline-first with local data persistence',
      ],
      tech_stack: ['Java', 'Kotlin', 'Android Studio', 'Jetpack Compose', 'Material Design'],
      github_url: 'https://github.com/manojagragari',
      apk_url: null,
      live_url: null,
      featured: true,
      order: 1,
      gradient: 'from-green-500/20 to-teal-500/20',
      accentColor: 'green',
    },
    {
      id: 5,
      title: 'Cricket Live & News Analytics App',
      category: 'android',
      description:
        'An Android app that delivers live cricket news, ICC team rankings, match history, and player performance insights through a dynamic interactive UI.',
      longDescription:
        'The Cricket Live & News Analytics App is an Android application built to combine real-time cricket news with match-focused analytics. It integrates a News API to surface the latest cricket updates, presents the Top 10 ICC Cricket Teams (2026), and lets users open individual team cards to explore match history, player statistics, and performance trends in an interactive Jetpack Compose interface.',
      features: [
        'Latest cricket news using API integration',
        'Top 10 ICC Teams list (2026)',
        'Clickable team cards to view match history',
        'Player statistics and performance analytics',
        'Match insights including total matches played, wins, and losses',
        'Dynamic UI with interactive components',
      ],
      tech_stack: ['Kotlin', 'Android Studio', 'Jetpack Compose', 'REST API Integration', 'JSON Data Handling'],
      github_url: 'https://github.com/manojagragari/Endterm1',
      apk_url: '/projects/cricket-live-news-analytics-app.apk',
      live_url: null,
      featured: true,
      order: 2,
      gradient: 'from-green-500/20 to-teal-500/20',
      accentColor: 'green',
    },
    {
      id: 6,
      title: 'Android Calculator App',
      category: 'android',
      description:
        'A fully functional calculator Android app built with XML UI and Kotlin logic for fast, responsive arithmetic operations.',
      longDescription:
        'The Android Calculator App is a clean and responsive mobile application developed using XML for the user interface and Kotlin for backend logic. It supports essential arithmetic operations such as addition, subtraction, multiplication, and division with real-time result updates and optimized layout behavior across Android devices.',
      features: [
        'Clean calculator UI designed using XML layouts',
        'Functional arithmetic operations (+, -, x, /)',
        'Button click handling and backend logic implementation',
        'Real-time result display',
        'Optimized layout for Android devices',
      ],
      tech_stack: ['Kotlin', 'Android Studio', 'XML Layout Design', 'Android SDK'],
      github_url: 'https://github.com/manojagragari/firstone',
      apk_url: '/projects/android-calculator-app.apk',
      live_url: null,
      featured: true,
      order: 3,
      gradient: 'from-green-500/20 to-teal-500/20',
      accentColor: 'green',
    },
  ],
  data_science: [
    {
      id: 7,
      title: 'Tesla Global Performance & Sustainability Dashboard',
      category: 'data_science',
      description:
        'A 7-page interactive Power BI dashboard that analyzes Tesla performance, production trends, regional growth, and sustainability impact with app-style navigation.',
      longDescription:
        'This project is a 7-page interactive Power BI report designed like an app experience with smooth navigation across analytical views. It covers yearly trend analysis, regional performance, model-wise behavior, production-focused insights, CO2 savings analytics, and a final leadership dashboard for KPI-driven decision-making. The report combines DAX-powered metrics, contextual slicers, and consistent visual storytelling for business insight and usability.',
      features: [
        'Home & navigation hub with button-based page transitions',
        'Year-wise analysis of deliveries, production, pricing, battery capacity, EV range, and CO2 savings',
        'Region-wise performance comparison using geographic and trend visuals',
        'Model-wise breakdown of deliveries, production, pricing, battery, range, and charging metrics',
        'Production-focused analysis of yearly output and capacity trends',
        'CO2 saved analytics for sustainability and emission reduction impact',
        'Final integrated leadership dashboard with key KPI overview',
      ],
      tech_stack: ['Power BI', 'DAX', 'Data Visualization', 'Data Analytics'],
      github_url: 'https://github.com/manojagragari',
      live_url: null,
      featured: true,
      order: 2,
      gradient: 'from-orange-500/20 to-yellow-500/20',
      accentColor: 'blue',
    },
  ],
};

export const skills = [
  {
    id: 1,
    category: 'Programming Languages',
    icon: '💻',
    color: 'cyan',
    borderColor: 'border-cyan-500/30',
    items: ['C++', 'Python', 'JavaScript', 'Java (Basic)', 'C (Basic)'],
  },
  {
    id: 2,
    category: 'Web Development',
    icon: '🌐',
    color: 'purple',
    borderColor: 'border-purple-500/30',
    items: ['React.js', 'Next.js', 'Django', 'DRF', 'Flask', 'Tailwind CSS', 'HTML5 & CSS3'],
  },
  {
    id: 3,
    category: 'Tools & IDEs',
    icon: '🛠️',
    color: 'blue',
    borderColor: 'border-blue-500/30',
    items: ['Git & GitHub', 'VS Code', 'Android Studio', 'Jupyter Notebook', 'Google Colab'],
  },
  {
    id: 4,
    category: 'Data & Analytics',
    icon: '📊',
    color: 'green',
    borderColor: 'border-green-500/30',
    items: ['Power BI', 'Pandas', 'NumPy', 'Matplotlib', 'Seaborn', 'Jupyter Notebook'],
  },
  {
    id: 5,
    category: 'Soft Skills',
    icon: '🧠',
    color: 'purple',
    borderColor: 'border-purple-500/30',
    items: ['Problem Solving', 'Team Collaboration', 'Analytical Thinking', 'Time Management'],
  },
];

export const certifications = [
  {
    id: 1,
    title: 'Frontend Developer (React)',
    issuer: 'HackerRank',
    year: 2026,
    url: 'https://www.hackerrank.com',
    color: 'cyan',
    icon: '⚛️',
    badge: 'bg-cyan-500/10 border-cyan-500/30 text-cyan-400',
  },
  {
    id: 2,
    title: 'Master Generative AI & Generative AI Tools',
    issuer: 'Infosys Springboard',
    year: 2025,
    url: 'https://springboard.infosys.com',
    color: 'purple',
    icon: '🤖',
    badge: 'bg-purple-500/10 border-purple-500/30 text-purple-400',
  },
  {
    id: 3,
    title: 'C++ with OOPs Programming Language',
    issuer: 'Cipher School',
    year: 2025,
    url: 'https://www.cipherschools.com',
    color: 'blue',
    icon: '🔷',
    badge: 'bg-blue-500/10 border-blue-500/30 text-blue-400',
  },
  {
    id: 4,
    title: 'JavaScript Algorithms & Data Structures',
    issuer: 'FreeCodeCamp',
    year: 2023,
    url: 'https://www.freecodecamp.org',
    color: 'green',
    icon: '📜',
    badge: 'bg-green-500/10 border-green-500/30 text-green-400',
  },
];

export const achievements = [
  {
    id: 1,
    title: '5 Star Python',
    platform: 'HackerRank',
    description:
      'Achieved 5 Star rating in Python on HackerRank by solving 50+ Python challenges across core programming, data structures, and algorithms.',
    year: 2026,
    icon: '⭐',
    color: 'cyan',
    gradient: 'from-cyan-500/10 to-transparent',
    borderColor: 'border-cyan-500/30',
    textColor: 'text-cyan-400',
  },
  {
    id: 2,
    title: 'Top 5 – University Hackathon',
    platform: 'Coding Ninjas',
    description:
      'Secured Top 5 position among 100+ teams at the University-level Hackathon (Coding Ninjas), building an innovative solution under 24 hours.',
    year: 2023,
    icon: '🏆',
    color: 'purple',
    gradient: 'from-purple-500/10 to-transparent',
    borderColor: 'border-purple-500/30',
    textColor: 'text-purple-400',
  },
  {
    id: 3,
    title: 'Working Prototype in 24 Hours',
    platform: 'Hackathon Sprint',
    description:
      'Built a complete, fully functional working prototype from scratch within a 24-hour Hackathon sprint, demonstrating rapid development skills.',
    year: 2023,
    icon: '⚡',
    color: 'blue',
    gradient: 'from-blue-500/10 to-transparent',
    borderColor: 'border-blue-500/30',
    textColor: 'text-blue-400',
  },
];

export const hobbies = [
  { id: 1, name: 'Cricket', icon: '🏏', description: 'Playing and following cricket tournaments passionately' },
  { id: 2, name: 'Tech Exploration', icon: '🔬', description: 'Exploring emerging technologies and latest frameworks' },
  { id: 3, name: 'Coding Challenges', icon: '💻', description: 'Solving problems on LeetCode, HackerRank, and more' },
  { id: 4, name: 'Problem Solving', icon: '🧩', description: 'Analytical thinking and algorithmic problem solving' },
];

export const contact = [
  {
    id: 1,
    label: 'LinkedIn',
    value: 'Manoj Agrahari',
    href: 'https://www.linkedin.com/in/manojagrahari',
    icon: 'linkedin',
    color: 'text-blue-400',
    borderColor: 'border-blue-500/30',
    bg: 'bg-blue-500/10',
    hoverBg: 'hover:bg-blue-500/20',
  },
  {
    id: 2,
    label: 'GitHub',
    value: 'manojagragari',
    href: 'https://github.com/manojagragari',
    icon: 'github',
    color: 'text-white',
    borderColor: 'border-white/20',
    bg: 'bg-white/5',
    hoverBg: 'hover:bg-white/10',
  },
  {
    id: 3,
    label: 'Instagram',
    value: 'manojagrahari72',
    href: 'https://instagram.com/manojagrahari72',
    icon: 'instagram',
    color: 'text-pink-400',
    borderColor: 'border-pink-500/30',
    bg: 'bg-pink-500/10',
    hoverBg: 'hover:bg-pink-500/20',
  },
  {
    id: 4,
    label: 'Email',
    value: 'manojagrahari7521@gmail.com',
    href: 'mailto:manojagrahari7521@gmail.com',
    icon: 'email',
    color: 'text-cyan-400',
    borderColor: 'border-cyan-500/30',
    bg: 'bg-cyan-500/10',
    hoverBg: 'hover:bg-cyan-500/20',
  },
  {
    id: 5,
    label: 'Phone',
    value: '+91 7307683053',
    href: 'tel:+917307683053',
    icon: 'phone',
    color: 'text-green-400',
    borderColor: 'border-green-500/30',
    bg: 'bg-green-500/10',
    hoverBg: 'hover:bg-green-500/20',
  },
];
